export const Themes = [
  { value: 'cerulean', name: 'Cerulean' },
  { value: 'cosmo', name: 'Cosmo' },
  { value: 'cyborg', name: 'Cyborg' },
  { value: 'darkly', name: 'Darkly' },
  { value: 'flatly', name: 'Flatly' },
  { value: 'journal', name: 'Journal' },
  { value: 'litera', name: 'Litera' },
  { value: 'lumen', name: 'Lumen' },
  { value: 'lux', name: 'Lux' },
  { value: 'materia', name: 'Materia' },
  { value: 'minty', name: 'Minty' },
  { value: 'pulse', name: 'Pulse' },
  { value: 'minty', name: 'Minty' },
  { value: 'sandstone', name: 'Sandstone' },
  { value: 'simplex', name: 'Simplex' },
  { value: 'sketchy', name: 'Sketchy' },
  { value: 'slate', name: 'Slate' },
  { value: 'solar', name: 'Solar' },
  { value: 'spacelab', name: 'Spacelab' },
  { value: 'superhero', name: 'Superhero' },
  { value: 'united', name: 'United' },
  { value: 'yeti', name: 'Yeti' }
]
